---
title: "Final Project"
subtitle: "The final project is a technical blog post demonstrating how to use a statistical model to answer an environmental data science question"
toc: true
format:
  html:
    markdown: +grid_tables
editor: source
---

Most of the course material in EDS 222 focuses on a single case study: the Exide battery recycling plant. We will explore data to answer environmental data science questions using statistical thinking. In your final project, you will apply these same skills to a case study of your own choosing. Using real data and appropriate analyses, you will write a **_technical blog post_** investigating an environmental question. 

::: {.callout-tip}

Every student in this class brings their own expertise, experience, and interests. As you develop your final project, remember that statistics is _a way of thinking_, not the rote application of mathematical or computational routines. The better you understand the nuances of your question, and the data that accompanies it, the richer your final project will be.

:::

Your **_technical blog post_** is a valuable contribution to your professional portfolio. The **analysis** in your project will demonstrate your competency in **_statistical thinking and tools_**. But on its own, an analysis has no impact. Just as importantly, your **writing** will show that you can **_think critically_** about questions and data, and **_communicate_** effectively about methods and interpretation.

In terms of complexity and detail, it should fall somewhere between a news article and peer-reviewed research. [This article on Medium](https://medium.com/@simon.chappatte2/richer-more-wasteful-investigating-the-household-waste-income-dynamic-5458b4373c10) is a good representative. Just be aware that it uses some techniques you won't see until EDS 241.

## Timeline

You will have multiple deliverables and checkpoints during the quarter that will scaffold your final project. These assignments are ungraded. Their purpose is to provide you with structure and instructor feedback early and often.

| Week | Deliverable | Description |
|----|----|----|
| 2 | Exploratory analysis | Numerical and graphical summaries of data relevant to your question. |
| 5 | Blog post proposal | A description of your question and data, with initial ideas for your analysis. |
| 9 | Blog post **first draft** | A completed first draft of your blog post. |
| Finals | Blog post **final draft** | The final draft of your blog post. |
: {tbl-colwidths="false"}

## Rubric

Your final project will be assessed according to the following rubric. 

### Question and data (15%)

An analysis means nothing without context! Before you show off your technical aptitude, give your audience motivation to care about your question.

**The blog post provides context and background for the question**

**The data are explained using text and figures**

**The theorized causal relationships are described with a DAG**

### Statistical model (35%)

It is often said, "All models are wrong, but some are useful." Describe your modeling approach in sufficient detail to understand both its utility as well as its limitations.

**The statistical model is explained conceptually and using formal statistical notation**

**The choice of model is justified based on the characteristics of the data and model assumptions**

**Potential limitations of the model and data are considered**

### Inference (35%)

Interpret your model in the context of your question and data. Remember that confidence intervals and p-values are tools for inference, not goals in of themselves. A robust interpretation of a non-significant result is far more compelling than a superficial treatment of a small p-value.

**Hypotheses are stated in plain language and with visualizations**

**Model estimates are presented with appropriate uncertainty**

**A hypothesis is tested and the evidence is interpreted**

### Professionalism (15%)

Your portfolio pieces will feature in your future job applications. This final project is not just about a grade in a class, it's a part of your job search. You're going to put a lot of work into this project - let's make sure hiring managers see the fruits of that labor.

**The overall appearance of the blog post (e.g., figures, code outputs) is portfolio-quality**

**The writing is comprehensible to a technical audience**

**The project repository is well-organized and appropriately documented**

